# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: botstatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import consts_pb2 as consts__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='botstatus.proto',
  package='badbot.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x62otstatus.proto\x12\x0f\x62\x61\x64\x62ot.messages\x1a\x0c\x63onsts.proto\"\x9e\x01\n\rSystemLoadAvg\x12\x0e\n\x06oneMin\x18\x01 \x01(\x02\x12\x0f\n\x07\x66iveMin\x18\x02 \x01(\x02\x12\x12\n\nfifteenMin\x18\x03 \x01(\x02\x12\x10\n\x08numCores\x18\x04 \x01(\x05\x12\x10\n\x08totalRam\x18\x05 \x01(\r\x12\x0f\n\x07\x66reeRam\x18\x06 \x01(\r\x12\x11\n\ttotalSwap\x18\x07 \x01(\r\x12\x10\n\x08\x66reeSwap\x18\x08 \x01(\r\"\xb5\x02\n\tBotStatus\x12\x14\n\x0clidarEnabled\x18\x01 \x01(\x08\x12\x1d\n\x15lidarRecordingEnabled\x18\x02 \x01(\x08\x12.\n\x04mode\x18\x03 \x01(\x0e\x32 .badbot.messages.OperationalMode\x12\x15\n\rappSrcEnabled\x18\x04 \x01(\x08\x12\x16\n\x0ewsVideoEnabled\x18\x05 \x01(\x08\x12\x18\n\x10telemetryEnabled\x18\x06 \x01(\x08\x12\x12\n\nimuHealthy\x18\x07 \x01(\x08\x12\x32\n\nsysLoadAvg\x18\x08 \x01(\x0b\x32\x1e.badbot.messages.SystemLoadAvg\x12\x12\n\ngpsHealthy\x18\t \x01(\x08\x12\x1e\n\x16motorControllerHealthy\x18\n \x01(\x08\x62\x06proto3'
  ,
  dependencies=[consts__pb2.DESCRIPTOR,])




_SYSTEMLOADAVG = _descriptor.Descriptor(
  name='SystemLoadAvg',
  full_name='badbot.messages.SystemLoadAvg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='oneMin', full_name='badbot.messages.SystemLoadAvg.oneMin', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fiveMin', full_name='badbot.messages.SystemLoadAvg.fiveMin', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fifteenMin', full_name='badbot.messages.SystemLoadAvg.fifteenMin', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numCores', full_name='badbot.messages.SystemLoadAvg.numCores', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalRam', full_name='badbot.messages.SystemLoadAvg.totalRam', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='freeRam', full_name='badbot.messages.SystemLoadAvg.freeRam', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalSwap', full_name='badbot.messages.SystemLoadAvg.totalSwap', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='freeSwap', full_name='badbot.messages.SystemLoadAvg.freeSwap', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=209,
)


_BOTSTATUS = _descriptor.Descriptor(
  name='BotStatus',
  full_name='badbot.messages.BotStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lidarEnabled', full_name='badbot.messages.BotStatus.lidarEnabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lidarRecordingEnabled', full_name='badbot.messages.BotStatus.lidarRecordingEnabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='badbot.messages.BotStatus.mode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appSrcEnabled', full_name='badbot.messages.BotStatus.appSrcEnabled', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wsVideoEnabled', full_name='badbot.messages.BotStatus.wsVideoEnabled', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='telemetryEnabled', full_name='badbot.messages.BotStatus.telemetryEnabled', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imuHealthy', full_name='badbot.messages.BotStatus.imuHealthy', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sysLoadAvg', full_name='badbot.messages.BotStatus.sysLoadAvg', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpsHealthy', full_name='badbot.messages.BotStatus.gpsHealthy', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motorControllerHealthy', full_name='badbot.messages.BotStatus.motorControllerHealthy', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=521,
)

_BOTSTATUS.fields_by_name['mode'].enum_type = consts__pb2._OPERATIONALMODE
_BOTSTATUS.fields_by_name['sysLoadAvg'].message_type = _SYSTEMLOADAVG
DESCRIPTOR.message_types_by_name['SystemLoadAvg'] = _SYSTEMLOADAVG
DESCRIPTOR.message_types_by_name['BotStatus'] = _BOTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemLoadAvg = _reflection.GeneratedProtocolMessageType('SystemLoadAvg', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMLOADAVG,
  '__module__' : 'botstatus_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.SystemLoadAvg)
  })
_sym_db.RegisterMessage(SystemLoadAvg)

BotStatus = _reflection.GeneratedProtocolMessageType('BotStatus', (_message.Message,), {
  'DESCRIPTOR' : _BOTSTATUS,
  '__module__' : 'botstatus_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.BotStatus)
  })
_sym_db.RegisterMessage(BotStatus)


# @@protoc_insertion_point(module_scope)
