# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmd_operational_mode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import consts_pb2 as consts__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmd_operational_mode.proto',
  package='badbot.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x63md_operational_mode.proto\x12\x0f\x62\x61\x64\x62ot.messages\x1a\x0c\x63onsts.proto\"J\n\x16\x43ommandOperationalMode\x12\x30\n\x06opMode\x18\x01 \x01(\x0e\x32 .badbot.messages.OperationalModeb\x06proto3'
  ,
  dependencies=[consts__pb2.DESCRIPTOR,])




_COMMANDOPERATIONALMODE = _descriptor.Descriptor(
  name='CommandOperationalMode',
  full_name='badbot.messages.CommandOperationalMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='opMode', full_name='badbot.messages.CommandOperationalMode.opMode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=135,
)

_COMMANDOPERATIONALMODE.fields_by_name['opMode'].enum_type = consts__pb2._OPERATIONALMODE
DESCRIPTOR.message_types_by_name['CommandOperationalMode'] = _COMMANDOPERATIONALMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandOperationalMode = _reflection.GeneratedProtocolMessageType('CommandOperationalMode', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDOPERATIONALMODE,
  '__module__' : 'cmd_operational_mode_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.CommandOperationalMode)
  })
_sym_db.RegisterMessage(CommandOperationalMode)


# @@protoc_insertion_point(module_scope)
