# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmdtoggle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import consts_pb2 as consts__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmdtoggle.proto',
  package='badbot.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63mdtoggle.proto\x12\x0f\x62\x61\x64\x62ot.messages\x1a\x0c\x63onsts.proto\"I\n\rCommandToggle\x12(\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x18.badbot.messages.Devices\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[consts__pb2.DESCRIPTOR,])




_COMMANDTOGGLE = _descriptor.Descriptor(
  name='CommandToggle',
  full_name='badbot.messages.CommandToggle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='badbot.messages.CommandToggle.device', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable', full_name='badbot.messages.CommandToggle.enable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=123,
)

_COMMANDTOGGLE.fields_by_name['device'].enum_type = consts__pb2._DEVICES
DESCRIPTOR.message_types_by_name['CommandToggle'] = _COMMANDTOGGLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandToggle = _reflection.GeneratedProtocolMessageType('CommandToggle', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDTOGGLE,
  '__module__' : 'cmdtoggle_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.CommandToggle)
  })
_sym_db.RegisterMessage(CommandToggle)


# @@protoc_insertion_point(module_scope)
