# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmdvel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmdvel.proto',
  package='badbot.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63mdvel.proto\x12\x0f\x62\x61\x64\x62ot.messages\"%\n\x0b\x43mdVelocity\x12\n\n\x02vX\x18\x01 \x01(\x05\x12\n\n\x02vY\x18\x02 \x01(\x05\x62\x06proto3'
)




_CMDVELOCITY = _descriptor.Descriptor(
  name='CmdVelocity',
  full_name='badbot.messages.CmdVelocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vX', full_name='badbot.messages.CmdVelocity.vX', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vY', full_name='badbot.messages.CmdVelocity.vY', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['CmdVelocity'] = _CMDVELOCITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CmdVelocity = _reflection.GeneratedProtocolMessageType('CmdVelocity', (_message.Message,), {
  'DESCRIPTOR' : _CMDVELOCITY,
  '__module__' : 'cmdvel_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.CmdVelocity)
  })
_sym_db.RegisterMessage(CmdVelocity)


# @@protoc_insertion_point(module_scope)
