# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lidarscan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lidarscan.proto',
  package='badbot.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0flidarscan.proto\x12\x0f\x62\x61\x64\x62ot.messages\"=\n\nLidarPoint\x12\r\n\x05\x61ngle\x18\x01 \x01(\x02\x12\r\n\x05range\x18\x02 \x01(\x02\x12\x11\n\tisTracked\x18\x03 \x01(\x08\"<\n\tLidarScan\x12/\n\nscanpoints\x18\x01 \x03(\x0b\x32\x1b.badbot.messages.LidarPointb\x06proto3'
)




_LIDARPOINT = _descriptor.Descriptor(
  name='LidarPoint',
  full_name='badbot.messages.LidarPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle', full_name='badbot.messages.LidarPoint.angle', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range', full_name='badbot.messages.LidarPoint.range', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isTracked', full_name='badbot.messages.LidarPoint.isTracked', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=97,
)


_LIDARSCAN = _descriptor.Descriptor(
  name='LidarScan',
  full_name='badbot.messages.LidarScan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scanpoints', full_name='badbot.messages.LidarScan.scanpoints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=159,
)

_LIDARSCAN.fields_by_name['scanpoints'].message_type = _LIDARPOINT
DESCRIPTOR.message_types_by_name['LidarPoint'] = _LIDARPOINT
DESCRIPTOR.message_types_by_name['LidarScan'] = _LIDARSCAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LidarPoint = _reflection.GeneratedProtocolMessageType('LidarPoint', (_message.Message,), {
  'DESCRIPTOR' : _LIDARPOINT,
  '__module__' : 'lidarscan_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.LidarPoint)
  })
_sym_db.RegisterMessage(LidarPoint)

LidarScan = _reflection.GeneratedProtocolMessageType('LidarScan', (_message.Message,), {
  'DESCRIPTOR' : _LIDARSCAN,
  '__module__' : 'lidarscan_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.LidarScan)
  })
_sym_db.RegisterMessage(LidarScan)


# @@protoc_insertion_point(module_scope)
