# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import cmdtoggle_pb2 as cmdtoggle__pb2
from . import botstatus_pb2 as botstatus__pb2
from . import consts_pb2 as consts__pb2
from . import cmd_operational_mode_pb2 as cmd__operational__mode__pb2
from . import cmdvel_pb2 as cmdvel__pb2
from . import videoframe_pb2 as videoframe__pb2
from . import imudata_pb2 as imudata__pb2
from . import gpsdata_pb2 as gpsdata__pb2
from . import lidarscan_pb2 as lidarscan__pb2
from . import obj_det_coords_pb2 as obj__det__coords__pb2
from . import telemetry_pb2 as telemetry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='badbot.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\x0f\x62\x61\x64\x62ot.messages\x1a\x0f\x63mdtoggle.proto\x1a\x0f\x62otstatus.proto\x1a\x0c\x63onsts.proto\x1a\x1a\x63md_operational_mode.proto\x1a\x0c\x63mdvel.proto\x1a\x10videoframe.proto\x1a\rimudata.proto\x1a\rgpsdata.proto\x1a\x0flidarscan.proto\x1a\x14obj_det_coords.proto\x1a\x0ftelemetry.proto\"\xde\x04\n\nBadMessage\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12-\n\x07msgType\x18\x02 \x01(\x0e\x32\x1c.badbot.messages.MessageType\x12,\n\x06status\x18\x03 \x01(\x0b\x32\x1a.badbot.messages.BotStatusH\x00\x12\x33\n\ttoggleCmd\x18\x04 \x01(\x0b\x32\x1e.badbot.messages.CommandToggleH\x00\x12\x39\n\x06opMode\x18\x05 \x01(\x0b\x32\'.badbot.messages.CommandOperationalModeH\x00\x12.\n\x06\x63mdVel\x18\x06 \x01(\x0b\x32\x1c.badbot.messages.CmdVelocityH\x00\x12\x31\n\nvideoFrame\x18\x07 \x01(\x0b\x32\x1b.badbot.messages.VideoFrameH\x00\x12+\n\x07imuData\x18\x08 \x01(\x0b\x32\x18.badbot.messages.ImuDataH\x00\x12/\n\tlidarScan\x18\t \x01(\x0b\x32\x1a.badbot.messages.LidarScanH\x00\x12+\n\x07gpsData\x18\n \x01(\x0b\x32\x18.badbot.messages.GpsDataH\x00\x12;\n\tobjCoords\x18\x0b \x01(\x0b\x32&.badbot.messages.ObjectDetectionCoordsH\x00\x12;\n\x0f\x64rivelineStatus\x18\x0c \x01(\x0b\x32 .badbot.messages.DrivelineStatusH\x00\x42\t\n\x07payloadb\x06proto3'
  ,
  dependencies=[cmdtoggle__pb2.DESCRIPTOR,botstatus__pb2.DESCRIPTOR,consts__pb2.DESCRIPTOR,cmd__operational__mode__pb2.DESCRIPTOR,cmdvel__pb2.DESCRIPTOR,videoframe__pb2.DESCRIPTOR,imudata__pb2.DESCRIPTOR,gpsdata__pb2.DESCRIPTOR,lidarscan__pb2.DESCRIPTOR,obj__det__coords__pb2.DESCRIPTOR,telemetry__pb2.DESCRIPTOR,])




_BADMESSAGE = _descriptor.Descriptor(
  name='BadMessage',
  full_name='badbot.messages.BadMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='badbot.messages.BadMessage.frame_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='badbot.messages.BadMessage.msgType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='badbot.messages.BadMessage.status', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='toggleCmd', full_name='badbot.messages.BadMessage.toggleCmd', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opMode', full_name='badbot.messages.BadMessage.opMode', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmdVel', full_name='badbot.messages.BadMessage.cmdVel', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='videoFrame', full_name='badbot.messages.BadMessage.videoFrame', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imuData', full_name='badbot.messages.BadMessage.imuData', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lidarScan', full_name='badbot.messages.BadMessage.lidarScan', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpsData', full_name='badbot.messages.BadMessage.gpsData', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='objCoords', full_name='badbot.messages.BadMessage.objCoords', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drivelineStatus', full_name='badbot.messages.BadMessage.drivelineStatus', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='badbot.messages.BadMessage.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=229,
  serialized_end=835,
)

_BADMESSAGE.fields_by_name['msgType'].enum_type = consts__pb2._MESSAGETYPE
_BADMESSAGE.fields_by_name['status'].message_type = botstatus__pb2._BOTSTATUS
_BADMESSAGE.fields_by_name['toggleCmd'].message_type = cmdtoggle__pb2._COMMANDTOGGLE
_BADMESSAGE.fields_by_name['opMode'].message_type = cmd__operational__mode__pb2._COMMANDOPERATIONALMODE
_BADMESSAGE.fields_by_name['cmdVel'].message_type = cmdvel__pb2._CMDVELOCITY
_BADMESSAGE.fields_by_name['videoFrame'].message_type = videoframe__pb2._VIDEOFRAME
_BADMESSAGE.fields_by_name['imuData'].message_type = imudata__pb2._IMUDATA
_BADMESSAGE.fields_by_name['lidarScan'].message_type = lidarscan__pb2._LIDARSCAN
_BADMESSAGE.fields_by_name['gpsData'].message_type = gpsdata__pb2._GPSDATA
_BADMESSAGE.fields_by_name['objCoords'].message_type = obj__det__coords__pb2._OBJECTDETECTIONCOORDS
_BADMESSAGE.fields_by_name['drivelineStatus'].message_type = telemetry__pb2._DRIVELINESTATUS
_BADMESSAGE.oneofs_by_name['payload'].fields.append(
  _BADMESSAGE.fields_by_name['status'])
_BADMESSAGE.fields_by_name['status'].containing_oneof = _BADMESSAGE.oneofs_by_name['payload']
_BADMESSAGE.oneofs_by_name['payload'].fields.append(
  _BADMESSAGE.fields_by_name['toggleCmd'])
_BADMESSAGE.fields_by_name['toggleCmd'].containing_oneof = _BADMESSAGE.oneofs_by_name['payload']
_BADMESSAGE.oneofs_by_name['payload'].fields.append(
  _BADMESSAGE.fields_by_name['opMode'])
_BADMESSAGE.fields_by_name['opMode'].containing_oneof = _BADMESSAGE.oneofs_by_name['payload']
_BADMESSAGE.oneofs_by_name['payload'].fields.append(
  _BADMESSAGE.fields_by_name['cmdVel'])
_BADMESSAGE.fields_by_name['cmdVel'].containing_oneof = _BADMESSAGE.oneofs_by_name['payload']
_BADMESSAGE.oneofs_by_name['payload'].fields.append(
  _BADMESSAGE.fields_by_name['videoFrame'])
_BADMESSAGE.fields_by_name['videoFrame'].containing_oneof = _BADMESSAGE.oneofs_by_name['payload']
_BADMESSAGE.oneofs_by_name['payload'].fields.append(
  _BADMESSAGE.fields_by_name['imuData'])
_BADMESSAGE.fields_by_name['imuData'].containing_oneof = _BADMESSAGE.oneofs_by_name['payload']
_BADMESSAGE.oneofs_by_name['payload'].fields.append(
  _BADMESSAGE.fields_by_name['lidarScan'])
_BADMESSAGE.fields_by_name['lidarScan'].containing_oneof = _BADMESSAGE.oneofs_by_name['payload']
_BADMESSAGE.oneofs_by_name['payload'].fields.append(
  _BADMESSAGE.fields_by_name['gpsData'])
_BADMESSAGE.fields_by_name['gpsData'].containing_oneof = _BADMESSAGE.oneofs_by_name['payload']
_BADMESSAGE.oneofs_by_name['payload'].fields.append(
  _BADMESSAGE.fields_by_name['objCoords'])
_BADMESSAGE.fields_by_name['objCoords'].containing_oneof = _BADMESSAGE.oneofs_by_name['payload']
_BADMESSAGE.oneofs_by_name['payload'].fields.append(
  _BADMESSAGE.fields_by_name['drivelineStatus'])
_BADMESSAGE.fields_by_name['drivelineStatus'].containing_oneof = _BADMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['BadMessage'] = _BADMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BadMessage = _reflection.GeneratedProtocolMessageType('BadMessage', (_message.Message,), {
  'DESCRIPTOR' : _BADMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.BadMessage)
  })
_sym_db.RegisterMessage(BadMessage)


# @@protoc_insertion_point(module_scope)
