# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: obj_det_coords.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='obj_det_coords.proto',
  package='badbot.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14obj_det_coords.proto\x12\x0f\x62\x61\x64\x62ot.messages\"W\n\x06\x43oords\x12\t\n\x01y\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01h\x18\x03 \x01(\x05\x12\t\n\x01w\x18\x04 \x01(\x05\x12\x12\n\nconfidence\x18\x05 \x01(\x05\x12\r\n\x05objId\x18\x06 \x01(\x05\"^\n\x15ObjectDetectionCoords\x12,\n\x0b\x63oordinates\x18\x01 \x03(\x0b\x32\x17.badbot.messages.Coords\x12\x17\n\x0fobject_at_angle\x18\x02 \x01(\x05\x62\x06proto3'
)




_COORDS = _descriptor.Descriptor(
  name='Coords',
  full_name='badbot.messages.Coords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='y', full_name='badbot.messages.Coords.y', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='badbot.messages.Coords.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='h', full_name='badbot.messages.Coords.h', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='w', full_name='badbot.messages.Coords.w', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='badbot.messages.Coords.confidence', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='objId', full_name='badbot.messages.Coords.objId', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=128,
)


_OBJECTDETECTIONCOORDS = _descriptor.Descriptor(
  name='ObjectDetectionCoords',
  full_name='badbot.messages.ObjectDetectionCoords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='badbot.messages.ObjectDetectionCoords.coordinates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='object_at_angle', full_name='badbot.messages.ObjectDetectionCoords.object_at_angle', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=224,
)

_OBJECTDETECTIONCOORDS.fields_by_name['coordinates'].message_type = _COORDS
DESCRIPTOR.message_types_by_name['Coords'] = _COORDS
DESCRIPTOR.message_types_by_name['ObjectDetectionCoords'] = _OBJECTDETECTIONCOORDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Coords = _reflection.GeneratedProtocolMessageType('Coords', (_message.Message,), {
  'DESCRIPTOR' : _COORDS,
  '__module__' : 'obj_det_coords_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.Coords)
  })
_sym_db.RegisterMessage(Coords)

ObjectDetectionCoords = _reflection.GeneratedProtocolMessageType('ObjectDetectionCoords', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTDETECTIONCOORDS,
  '__module__' : 'obj_det_coords_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.ObjectDetectionCoords)
  })
_sym_db.RegisterMessage(ObjectDetectionCoords)


# @@protoc_insertion_point(module_scope)
