# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='telemetry.proto',
  package='badbot.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ftelemetry.proto\x12\x0f\x62\x61\x64\x62ot.messages\"0\n\x0f\x44rivelineStatus\x12\r\n\x05vLeft\x18\x01 \x01(\x05\x12\x0e\n\x06vRight\x18\x02 \x01(\x05\x62\x06proto3'
)




_DRIVELINESTATUS = _descriptor.Descriptor(
  name='DrivelineStatus',
  full_name='badbot.messages.DrivelineStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vLeft', full_name='badbot.messages.DrivelineStatus.vLeft', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vRight', full_name='badbot.messages.DrivelineStatus.vRight', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['DrivelineStatus'] = _DRIVELINESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DrivelineStatus = _reflection.GeneratedProtocolMessageType('DrivelineStatus', (_message.Message,), {
  'DESCRIPTOR' : _DRIVELINESTATUS,
  '__module__' : 'telemetry_pb2'
  # @@protoc_insertion_point(class_scope:badbot.messages.DrivelineStatus)
  })
_sym_db.RegisterMessage(DrivelineStatus)


# @@protoc_insertion_point(module_scope)
